[package]
name = "docgen"
version = "0.1.0"
edition = "2024"

[dependencies]
talaria = { path = "../talaria" }
rhai-autodocs = "0.8"
handlebars = "6.3.2"
serve = "0.0.1"
serde = "1.0.219"
serde_json = "1.0.140"
