name: Test Talaria 

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.12.2
    
      - name: Test Talaria
        run: |
          cd talaria
          cargo test
