name: Tests 

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tartarus:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.12.2

      - name: Test Tartarus
        run: |
          cd tartarus
          cargo test --verbose
